spring:
  datasource:
    url: jdbc:mysql://root:123456798@localhost:3306/messageboard?serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379

jwt:
  secret-key: 4297f44b13955235245b2497399d7a93

avatar:
  save-path: '/home/kale/tmp/'

base-url: 'http://127.0.0.1:8080/api/attachment/'

comment:
  page-size: 10

kaptcha:
  height: 40
  width: 200
  content:
    length: 4
    source: abcdefghjklmnopqrstuvwxyz23456789
    space: 2
  font:
    color: black
    name: Arial
    size: 35
  background-color:
    from: white
    to: white
  border:
    enabled: false
    color: black
    thickness: 1
