spring:
  datasource:
    url: jdbc:mysql://root:123456798@localhost:3306/messageboard?serverTimezone=UTC&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379

jwt:
  secret-key: 4297f44b13955235245b2497399d7a93
