spring:
  datasource:
    url: jdbc:mysql://db:3306/messageboard?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    database: 1
    host: redis

jwt:
  secret-key: 4297f44b13955235245b2497399d7a93

avatar:
  save-path: 'src/main/resources/avatar'

base-url: '/api/attachment/'

comment:
  page-size: 10

kaptcha:
  height: 40
  width: 200
  content:
    length: 4
    source: abcdefghjklmnopqrstuvwxyz23456789
    space: 2
  font:
    color: black
    name: Arial
    size: 35
  background-color:
    from: white
    to: white
  border:
    enabled: false
    color: black
    thickness: 1
